FROM node:22.13.0 AS base
WORKDIR /usr/src/app
COPY ./frontend/package.json ./
COPY ./frontend/yarn.lock ./
COPY ./frontend/entrypoint.sh ./

FROM base AS debug
COPY ./frontend .
EXPOSE 3000
ENTRYPOINT [ "/usr/src/app/entrypoint.sh" ]
CMD ["yarn", "start"]


FROM base AS build
# TARGETPLATFORM is used to determine the architecture of the build environment. It is auto set by Docker's buildkit when building multi-platform images.
ARG TARGETPLATFORM
COPY ./frontend .
RUN ./entrypoint.sh
RUN yarn build


FROM nginx:alpine AS prod
# Copy built React app from build stage
COPY --from=build /usr/src/app/build /usr/share/nginx/html

# Copy nginx configuration
COPY scripts/docker/nginx.conf /etc/nginx/conf.d/default.conf

# Copy environment injection script
COPY scripts/docker/inject-env.sh /docker-entrypoint.d/40-inject-env.sh

# Make the injection script executable
RUN chmod +x /docker-entrypoint.d/40-inject-env.sh

EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
