FROM node:22.13.0 AS base
WORKDIR /usr/src/app
COPY ./frontend/package.json ./
COPY ./frontend/yarn.lock ./
COPY ./frontend/entrypoint.sh ./

FROM base AS debug
COPY ./frontend .
EXPOSE 3000
ENTRYPOINT [ "/usr/src/app/entrypoint.sh" ]
CMD ["yarn", "start"]


FROM base AS build
# TARGETPLATFORM is used to determine the architecture of the build environment. It is auto set by Docker's buildkit when building multi-platform images.
ARG TARGETPLATFORM
RUN ./entrypoint.sh
COPY ./frontend .

FROM nginx:alpine AS prod
# Install node and yarn in the production container
RUN apk add --no-cache nodejs npm yarn

# Copy source code from build stage
COPY --from=build /usr/src/app /usr/src/app
COPY scripts/docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY scripts/docker/startup.sh /usr/local/bin/startup.sh

# Make sure the script is executable
RUN chmod +x /usr/local/bin/startup.sh

EXPOSE 3000
CMD ["/usr/local/bin/startup.sh"]
